:virgo-name: Virgo
:version: 3.7.0.RC01

:umbrella-virgo-name: Eclipse Virgo
:tomcat-product-name: Virgo for Apache Tomcat
:tomcat-product-name-short: VTS
:jetty-product-name: Virgo Jetty Server
:jetty-product-name-short: VJS
:kernel-product-name: Virgo Kernel
:kernel-product-name-short: VK
:nano-product-name: Virgo Nano
:nano-product-name-short: VN
:user-guide: link:../../virgo-user-guide/html/index.html[User Guide]
:tooling-guide: link:../../virgo-tooling-guide/html/index.html[Tooling Guide]

:gemini-blueprint-guide: https://www.eclipse.org/gemini/blueprint/documentation/reference/2.0.0.RELEASE/html/index.html[Eclipse Gemini Blueprint Reference Guide]

:spring-framework-version: 4.2.9.RELEASE

:homepage: https://www.eclipse.org/virgo
:ebr: http://www.eclipse.org/ebr[EBR]

:imagesdir: assets/images

anchor:introduction[]

== Introduction

This User Guide covers the {tomcat-product-name} ({tomcat-product-name-short}), the {jetty-product-name}
({jetty-product-name-short}) and the {kernel-product-name} ({kernel-product-name-short}), although it emphasises the
{tomcat-product-name-short} since that is likely to apply to more users.


=== A Note for {kernel-product-name} Users

{kernel-product-name} users can be reassured that the majority of the information
in this Guide is directly applicable to the {kernel-product-name} and they can simply ignore the web-related sections.

=== A Note for {jetty-product-name} Users

{jetty-product-name} users can be reassured that the majority of the information
in this Guide is directly applicable to the {jetty-product-name} and they can simply ignore the {tomcat-product-name} specific sections.

=== A Note for {nano-product-name} Users

{nano-product-name} is a bit different than {kernel-product-name-short} and {tomcat-product-name-short}.
It is the smallest Virgo offering and takes performance to its limits, almost instantly booting up.
{nano-product-name} users will find a number of sections in this guide useful but sections that refer to
*plans, PARs and configuration deployment, regions, application scoping and libraries support*
are NOT relevant for {nano-product-name} or {nano-product-name-short} and should be ignored.
This Virgo distribution relies on p2 for its provisioning, therefore is bound to p2 concepts such as *p2 features and update sites*.
Note also that {nano-product-name} includes Gemini.Web as its default web container implementation and uses its default configuration.

